### ISSUE TITLE
Editor for creating posts

### ISSUE THREAD

**Issue by Saga-sanga** [Saga-sanga/t3-apologia#3]
**Tasks list**

- [ ] Implement different plugins for editor.js
- [x] Create title input
- [ ] Create navigation (back button)
- [ ] Create image input
- [ ] Create aws s3 endpoint to manage uploaded images
- [ ] Create endpoint to update post
- [x] Create endpoint to delete posts
- [ ] Create endpoint to publish/unpublish post
